# Spring
spring:
  datasource:
    url: jdbc:mysql://${cloud.aws.rds.instances.0.endpoint}:3306/${cloud.aws.rds.instances.0.databaseName}
    username: ${cloud.aws.rds.instances.0.username}
    password: ${cloud.aws.rds.instances.0.password}

    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 15000
      validation-timeout: 5000
      read-only: false
      connection-init-sql: "SET SESSION sql_mode='TRADITIONAL,NO_AUTO_VALUE_ON_ZERO,ONLY_FULL_GROUP_BY'"
  thymeleaf:
    cache: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: never
      encoding: UTF-8
  session:
    store-type: redis
  redis:
    port: 6379
  cache:
    type: simple
#    redis:
#      time-to-live: 43200000

logging:
  level:
    root: WARN

# AWS
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-1
    instance:
      data:
        enabled: true
    s3:
      endpoint: https://s3.ap-northeast-1.amazonaws.com
    rds:
      enabled: false