# Spring
spring:
  datasource:
    url: jdbc:mysql://localhost/sakemandb?useSSL=false&allowPublicKeyRetrieval=true
    username: sakemanuser
    password: sakemanpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: true
  sql:
    init:
      mode: never
      encoding: UTF-8
  thymeleaf:
    cache: false
      
# AWS
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-1
    instance:
      data:
        enabled: false
    credentials:
      instanceProfile: false
      profileName: default
    
