# Spring
spring:
  datasource:
    url: jdbc:mysql://localhost/sakemandb?useSSL=false&allowPublicKeyRetrieval=true
    username: sakemanuser
    password: sakemanpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
      
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: true
  sql:
    init:
      mode: never
      encoding: UTF-8
  thymeleaf:
    cache: false
  session:
    store-type: none
  cache:
    type: simple
    
logging:
  level:
    org:
      hibernate:
        SQL : DEBUG
        type:
            descriptor:
                sql:
                    BasicBinder: TRACE
       
    
management:
  health:
    redis:
      enabled: false  
      
# AWS
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-1
    instance:
      data:
        enabled: false
    credentials:
      instanceProfile: false
      profileName: default
    
