# Spring
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: sakeman
  config:
    import: 'aws-parameterstore:'
  servlet:
    multipart:
      max-file-size: 10MB
      
# UploadFileSaveDir
#attached:
#  file:
#    path: 

# Tomcat
#server:
#  servlet:
#    context-path: /sakeman

# セッション＆クッキー有効期限
server:
  servlet:
    session:
      timeout: 86400
      cookie:
        max-age: 86400

# AWS
aws:
  paramstore:
    enabled: true
    region: ap-northeast-1
    prefix: /config
    profileSeparator: _
    failFast: true
