INSERT INTO manga(title, title_kana, registered_at, updated_at, display_flag, delete_flag, volume, publisher, published_in, synopsis, calligraphy)
 VALUES ("おはよう！スパンク なかよし60周年記念版", "オハヨウ！スパンク ナカヨシ60シュウネンキネンバン", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 0, 7, "講談社", "なかよし", "パパのいない愛子にとって、いちばんの話し相手だった愛犬パピーがトラックにはねられて死んでしまったのです。かなしみにくれる愛子の前に現れたのが、それはもうおかしな犬、スパンクでした。そしていつの間にか、ちゃっかり愛犬の座を獲得しちゃって……。すっかり仲良くなった二人がくりひろげる、さわやかタッチのラブリーストーリー、完全復刻です！", "73be83e9-228c-43c5-ac37-75cd9c8ff7c4.jpeg");
INSERT INTO manga(title, title_kana, registered_at, updated_at, display_flag, delete_flag, volume, publisher, published_in, synopsis, calligraphy)
 VALUES ("スパンクのWAOWAO探偵団", "スパンクノワオワオタンテイダン", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 0, 1, "講談社", "なかよし", "『おはよう！　スパンク』の番外編にあたる、スパンクの冒険ストーリー！　飼い主・愛ちゃんがパリへ行っている間に、スパンクが誘拐事件に巻き込まれちゃった。身代金目的でさらわれたのは、スパンクに瓜二つだという名家の飼い犬・竜馬。その影武者をすることになったスパンクだけど、沈着冷静でクールな竜馬の真似は大変で……!?　おなじみスパンクが大活躍！　表題作の他に、『1月なかば春の色』も同時収録。", "a29feac9-eff9-4a4d-a617-9f885f1de35f.jpeg");
INSERT INTO manga(title, title_kana, registered_at, updated_at, display_flag, delete_flag, volume, publisher, published_in, synopsis, calligraphy)
 VALUES ("あさひなぐ", "アサヒナグ", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 0, 34, "小学館", "ビッグコミックスピリッツ", "二ツ坂高校一年、東島旭（とうじま・あさひ）、15歳。中学まで美術部だった旭は、「薙刀は高校部活界のアメリカンドリーム！スポーツに縁のなかった人間でも全国にその名を轟かすことができる」といううたい文句に感激し、薙刀部に入部する。痴漢を蹴りで撃退する強き女、あこがれの先輩、宮路真春（みやじ・まはる）、同じ一年生で剣道経験者の八十村将子（やそむら・しょうこ）と長身が悩みの紺野さくら（こんの・さくら）…旭と仲間達“なぎなたガールズ”の強く！楽しく!!美しい!!!物語が始まる――", "e13c281f-1001-4eea-af74-5ad3d89dc262.jpg");
INSERT INTO manga(title, title_kana, registered_at, updated_at, display_flag, delete_flag, volume, publisher, published_in, synopsis, calligraphy)
 VALUES ("みどりのマキバオー", "ミドリノマキバオー", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 0, 10, "集英社", "週刊少年ジャンプ", "日本競馬史上、かつてない珍馬・珍獣が出現。体は小さいが走るのは速い、犬の様な白毛馬、みどり牧場一の競走馬ミドリマキバオー!!意気揚揚と新馬戦に臨もうとするが、華々しいデビューを飾れるか…!?競馬界に旋風を巻き起こせ!!＜おちゃめなコミック童話＞みどりのマキバオー収録", "94ab8878-6760-4630-93a2-c0c3798a855c.jpeg");
INSERT INTO manga(title, title_kana, registered_at, updated_at, display_flag, delete_flag, volume, publisher, published_in, synopsis, calligraphy)
 VALUES ("柔道部物語", "ジュウドウブモノガタリ", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 0, 11, "講談社", "週刊ヤングマガジン", "俺は三五十五（さんご・じゅうご）。高校に入学したばかりで何も知らない俺は、先輩たちの甘い言葉に乗せられて柔道部に入ることにした。ところが、入部したとたん、先輩たちの態度が豹変。シゴキはあるわ、坊主頭にさせられるわ、もちろん女の子との交流会なんて真っ赤なウソ。でも、一度やると決めた柔道だ。強くなってみせるぞ――!!読み出したら止まらない!!珠玉の本格柔道コメディ!!", "bdd1cf4c-e60b-43c5-9f82-3fe3b30fadbb.jpg");
INSERT INTO manga(title, title_kana, registered_at, updated_at, display_flag, delete_flag, volume, publisher, published_in, synopsis, calligraphy)
 VALUES ("タッチ", "タッチ", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 0, 11, "小学館", "週刊少年サンデー", "努力という言葉に縁のない兄・上杉達也と、何事にも一生懸命努力する弟・上杉和也。二人は、双子の兄弟。隣の喫茶店「南風」の一人娘・浅倉南とは幼なじみ。三人の「青春」から、目が離せない……！", "f6c6d499-035b-4dc9-8c54-7055f227d466.jpg");

INSERT INTO user(username, registered_at, updated_at, delete_flag, password, email, role, self_intro, img) VALUES ("ktaro", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "0", "", "hideaki.sakai.75@gmail.com", "管理者", "はじめてマンガを読みはじめたのは、小1の夏休みに新潟のばあちゃんちに行ったときに、いとこが定期購読していたジャンプでキン肉マン…", "user-icon.jpg");
INSERT INTO user(username, registered_at, updated_at, delete_flag, password, email, role, self_intro, img) VALUES ("酒チャビン", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "0", "$2a$08$clh9XaYYznpX9WDqySgiCuUu4znpSeu2oJi5l2Q00UJs42Llrbd7S", "75@gmail.com", "管理者", "はじめてマンガを読みはじめたのは、小1の夏休みに新潟のばあちゃんちに行ったときに、いとこが定期購読していたジャンプでキン肉マン…", "profileIcon_snoo482a9ec3-9dcd-475c-a992-db86e918cb03-headshot.png");
INSERT INTO user(username, registered_at, updated_at, delete_flag, password, email, role, self_intro, img) VALUES ("DeSio", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "0", "$2a$08$clh9XaYYznpX9WDqySgiCuUu4znpSeu2oJi5l2Q00UJs42Llrbd7S", "desio@gmail.com", "管理者", "はじめてマンガを読みはじめたのは、小1の夏休みに新潟のばあちゃんちに行ったときに、いとこが定期購読していたジャンプでキン肉マン…", "user-icon.jpg");

INSERT INTO author(name, name_kana, registered_at, updated_at, delete_flag, display_flag, profile, img) VALUES ("たかなししずえ", "タカナシシズエ", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "0", "1", "たかなし しずえ（8月31日 - ）は、日本の漫画家。「たかなし」と「しずえ」との間にハートマークが入っている場合がある。", "");
INSERT INTO author(name, name_kana, registered_at, updated_at, delete_flag, display_flag, profile, img) VALUES ("雪室俊一", "ユキムロシュンイチ", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "0", "1", "雪室 俊一（ゆきむろ しゅんいち、1941年1月11日 - ）は、神奈川県横浜市出身の男性脚本家。シナリオ研究所卒業。日本放送作家協会会員。別名義に、西浦あかね、洋駿太郎がある。", "");
INSERT INTO author(name, name_kana, registered_at, updated_at, delete_flag, display_flag, profile, img) VALUES ("こざき亜衣", "コザキアイ", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "0", "1", "こざき 亜衣（こざき あい、1982年2月22日 - ）は、日本の女性漫画家・イラストレーター。千葉県出身。多摩美術大学映像演劇学科中退。漫画家・イラストレーターのコザキユースケは実兄。", "");
INSERT INTO author(name, name_kana, registered_at, updated_at, delete_flag, display_flag, profile, img) VALUES ("つの丸", "ツノマル", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "0", "1", "つの丸（つのまる、本名：津野 将昭（つの まさあき）[2]、1970年5月27日 - ）は、日本の漫画家。千葉県千葉市出身。千葉市立稲毛高等学校卒業。男性[1]。血液型はA型。", "");
INSERT INTO author(name, name_kana, registered_at, updated_at, delete_flag, display_flag, profile, img) VALUES ("小林まこと", "コバヤシマコト", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "0", "1", "小林 まこと（こばやし まこと、1958年〈昭和33年〉5月13日 - ）は、日本の漫画家。新潟県新潟市出身。本名：小林誠。主に講談社の漫画雑誌にて執筆。プロレス、格闘技好きで知られる。", "");

INSERT INTO review(title, content, rating, registered_at, updated_at, delete_flag, manga_id, user_id) VALUES ("泣ける・・動物との友情物語！！", "子どものころアニメをやっていたのか、なんとなく印象にはあったのですが、内容はほぼ知らず、ただ主人公のスパンク（犬）が昔飼っていたうさぎを彷彿とさせるところがあったので、なんとなく気になって読んでみました。結果・・面白い！！アニメの記憶では、なんとなくスパンクのルックスからして、ドタバタ生活コメディかと勝手に想像していたのですが、全然違いました！少女漫画らしく、飼い主の甘酸っぱい恋愛話などもあるのですが、メインは飼い主とスパンクとの尊い友情の物語だと思います。スパンクが信じられないくらい愛くるしく、性格もすごく良いので、大ファンになりました！（けっこう昔のマンガ特有の、悲惨でシリアスな状況に追い込まれがちな描写もあります）ちょっと調べたところ、ちょうど今発売中のなかよし2022年9月号から期間限定新れんさいで続編のような4コマが掲載されているのと、なんと「おはよう！スパンク HAPPYステショセット」（ポーチ、シャーペン、定規）がついているとのことで、思わず今日朝イチくまざわに購入しに行ってしまいました。ゆるキャンのようなほんわりとした作品が好きな方や、感動ものが好きな方には全員にオススメできる作品です！！ぜひ試し読みでもいいので読んでみてください！！！", "5", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "0", "1", "2");
INSERT INTO review(title, content, rating, registered_at, updated_at, delete_flag, manga_id, user_id) VALUES ("大好きなスパンクのはみだし編！！！", "なんかスパンクが好きすぎるのですが、「『おはよう！スパンク』はみだし編」ということで、探偵ものですね。飼い主の愛ちゃんがパリに行っている間に事件に巻き込まれます！（なかよしの昭和55年9月号のふろくだったようです）冒頭からスパンクの愛くるしさ爆発で、1巻の2/3ほどの長さしかありませんが、スパンクの物語をまた楽しめてすごく充実した三連休となりました。「だいたい 運動神経は わるいしさ、たべものには いやしいし、すぐ わるのりするし、おまけに 臆病でさ」とボロクソにこき下ろされてしまいますが、スパンクだってスパンクなりにいっしょうけんめいやってくれてるんです。最後は犬同士の友情＆犬と猫との友情＆犬と人間との友情でなんとか事件解決！かなり危険な事件でしたが、スパンクが心やさしく、いいやつだからこそ皆が力を合わせてくれるのですね。わたしもかくありたいと思います。あと併録の「1月なかば春の色」は、スパンクよりもうちょい甘酸っぱめな恋物語のテイスト感が強めですが、若者の成長も描かれてたり、命の大切さを感じられたりで、けっこう楽しめました！スパンクっぽい犬もちょろっと出てます！", "5", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "0", "2", "2");
INSERT INTO review(title, content, rating, registered_at, updated_at, delete_flag, manga_id, user_id) VALUES ("「何者でもない」人たちのものがたり", "とあとがきで先生がおっしゃってるとおりのマンガです。まず主人公がいなか臭いです。絶妙ないなか臭さで、いなか臭すぎるとマンガ臭くなってしまうのですが、本当にいそうで絶妙です。ですがそれも素晴らしいです。よく『ちはやふる』が少女マンガの皮をかむった少年マンガと言われていて、私すごく好きなのですが、それに近いスポ根的な部分もかなりあり、すごくこちらの作品も面白いです。つうか、よく高評価されてるのは見かけてはいましたが、こぎゃん面白いマンガとは思ってもみませんでした。ただ、若干こちらの方が少年度が低いというか、女子っぽい部分が多めでしょうか。そこも良かったと思います。つうか最初の数巻は、わざとなのか描写不足なのか、別にそこまで皆頑張ってる感じがせず、したがって主人公のチームが負けようが特に何の感傷もなかったのですが（どちらかというと敵役の一堂選手の方が言い分もわかるし思い入れがありました。一堂という苗字も、世界的名作である奇面組へのリスペクトが感じられて好感が持てます）、途中からかなりよくなってくるので、5〜６巻くらいまでは諦めないで続けてほしいです！あと、こういう「冴えない主人公が強い人に憧れて頑張って強くなる」っていうのは定番ですが、本作品がレアなのは、憧れだった強い人から何かを受け継いで強くなった主人公が、憧れられる側だった人間に何かを返すところまで描かれている点です。主に最終巻の話になってしまうのですが、大体前述の定番ものですと、最終巻は緊迫したストーリー運びながらも、どこか「どうせ優勝やろ」みたいなところもあるのですが、本作は最後の最後一捻りが聞いていてすごく心に残る作品となりました。個人的には紺野選手とやす子が好きですね。すごくいいと思います。というか、このマンガの特徴として、マンガ自体とかストーリーとかが好きっていうよりも、若干脇役っぽい方も含めた登場人物のことがすごく好きになるっていう点があります。あまりそういった経験がなかったので、それも高評価をつけた理由です。推しってこういうところからスタートするのですかね？？いずれにしても、自分ががんばっている人にはまず間違いなくオススメできる世界レベルの名作ですので、ぜひ読んでみてください！！全34巻と、完全に読者の心を入り口から折りにかかってきますが、がんばれる人なら大丈夫です！！！がんばってない人、頑張れる自信がない人はハンチョウを読みましょう！", "5", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "0", "3", "2");
INSERT INTO review(title, content, rating, registered_at, updated_at, delete_flag, manga_id, user_id) VALUES ("つらいことがあった時などに何度も読み返します！", "わたしがジャンプを定期購読していた時に連載していたのですが、そのときは完全にナメていて、ろくに読みもせず、絵柄やウ○コギャグなどからお子様向けマンガと決めつけていました。読んだのは30を超えてからで、大人中の大人になってからだったのですが、マキバオーが不遇な仔馬時代から努力と友情によって勝利を掴むという、まさにジャンプ正統のスポ根マンガと気づき、そしてハマり、気づけば同日に何回も書店に買い足しに行くという事態になっていました（最初3巻くらい買って、当日に読み終わって、すぐもう2巻買いにいって・・・みたいな繰り返しです。歩いて5分のところに山下書店があって本当によかったです）。読んだ当時は、すぐにマイベストマンガの1位か、それか2位、あるいは3位くらいには入りました！！30を過ぎていまさらなぜマキバオーを読むことになったのか、今となっては全く覚えてないのですが、とにかくそのきっかけに本当に感謝しています。今でもつらいときは、マキバオーも頑張ってるから！と勇気をもらっています。あのときマキバオーを読んでいなかったら、今の私はないと思います。ありがとう、マキバオー。そしてありがとう、つの丸先生！絵柄やウ○コギャグで敬遠されている方がいれば、一度騙されたと思って3巻くらいまで読んでみてください！！きっと損はさせないと思います！！！ウ○コギャグはジョジョの荒木先生もかなり多用されてますし、作品の凄さとはまた別だと思うので！！！", "5", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "0", "4", "2");
INSERT INTO review(title, content, rating, registered_at, updated_at, delete_flag, manga_id, user_id) VALUES ("柔道部物語の感想", "高校くらいの時に読んでいて、その時もすごく面白かったのですが、大人になってから再読。自らも色々な経験をしてきたからこそわかることというか、高校時代は単純に「全国制覇がんばれ！熱い！」という感想だったのが、大人になってから読むとなんか色々込み上げるものがあって、3度ほど泣きました・・・特に初めて石川選手に勝つところが号泣。。王道のスポーツ漫画が好きな方はぜひ読んでみてください！", "5", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "0", "5", "2");

INSERT INTO manga_author(manga_id, author_id, registered_at, updated_at) values (1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO manga_author(manga_id, author_id, registered_at, updated_at) values (1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO manga_author(manga_id, author_id, registered_at, updated_at) values (2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO manga_author(manga_id, author_id, registered_at, updated_at) values (3, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO manga_author(manga_id, author_id, registered_at, updated_at) values (4, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO manga_author(manga_id, author_id, registered_at, updated_at) values (5, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO uclist(title, description, registered_at, updated_at, delete_flag, user_id) values ("件名", "最高のリスト", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 2);

INSERT INTO uclist_manga(manga_id, uclist_id, registered_at, updated_at, delete_flag) values (1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO uclist_manga(manga_id, uclist_id, registered_at, updated_at, delete_flag) values (2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO uclist_manga(manga_id, uclist_id, registered_at, updated_at, delete_flag) values (3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO uclist_manga(manga_id, uclist_id, registered_at, updated_at, delete_flag) values (4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO uclist_manga(manga_id, uclist_id, registered_at, updated_at, delete_flag) values (5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);